# items.py

import scrapy


class InspectionItem(scrapy.Item):
    date = scrapy.Field()
    type = scrapy.Field()
    original_status = scrapy.Field()
    corrective_status = scrapy.Field()
    status_updated = scrapy.Field()
    report_url = scrapy.Field()
    va_shsi = scrapy.Field()
    va_complaint_related = scrapy.Field()
    va_violations = scrapy.Field()
    mt_inspector_name = scrapy.Field()
    md_regulation = scrapy.Field()
    md_finding = scrapy.Field()
    md_inspection_status = scrapy.Field()
    # South Carolina specific
    sc_alert_count = scrapy.Field()
    sc_alert_resolved_count = scrapy.Field()
    sc_deficiencies = scrapy.Field()
    # North Carolina specific
    nc_violations = scrapy.Field()
    # Rhode Island specific
    ri_compliance = scrapy.Field()
    ri_licensor = scrapy.Field()
    # West Virginia specific
    wv_corrective_action_plan_start = scrapy.Field()
    wv_corrective_action_plan_end = scrapy.Field()
    wv_non_compliance_code = scrapy.Field()
    wv_outcome_code = scrapy.Field()
    wv_issue_completed_date = scrapy.Field()

    # Arizona specific
    az_regulation = scrapy.Field()
    az_decision_correction = scrapy.Field()
    az_date_resolved = scrapy.Field()
    az_civil_penalty = scrapy.Field()
    az_enforcement_name = scrapy.Field()

    # Florida specific
    fl_has_violation = scrapy.Field()
    fl_inspection_id = scrapy.Field()


class ProviderItem(scrapy.Item):
    # This defines all the possible columns for your final CSV file.
    provider_name = scrapy.Field()
    license_number = scrapy.Field()
    license_holder = scrapy.Field()
    provider_type = scrapy.Field()
    status = scrapy.Field()
    status_date = scrapy.Field()
    sutq_rating = scrapy.Field()
    address = scrapy.Field()
    latitude = scrapy.Field()
    longitude = scrapy.Field()
    phone = scrapy.Field()
    email = scrapy.Field()
    provider_website = scrapy.Field()
    administrator = scrapy.Field()
    capacity = scrapy.Field()
    hours = scrapy.Field()
    ages_served = scrapy.Field()
    infant = scrapy.Field()
    toddler = scrapy.Field()
    preschool = scrapy.Field()
    school = scrapy.Field()
    county = scrapy.Field()
    scholarships_accepted = scrapy.Field()
    license_begin_date = scrapy.Field()
    license_expiration = scrapy.Field()
    deficiencies = scrapy.Field()
    languages = scrapy.Field()

    # Virginia specific fields
    va_license_type = scrapy.Field()
    va_inspector = scrapy.Field()
    va_current_subsidy_provider = scrapy.Field()
    # Texas specific fields
    tx_rising_star = scrapy.Field()
    tx_operation_id = scrapy.Field()
    tx_agency_number = scrapy.Field()
    # California specific fields
    ca_regional_office = scrapy.Field()
    ca_license_first_date = scrapy.Field()
    ca_closed_date = scrapy.Field()
    ca_citation_numbers = scrapy.Field()
    ca_poc_dates = scrapy.Field()
    ca_all_visit_dates = scrapy.Field()
    ca_inspection_visit_dates = scrapy.Field()
    ca_other_visit_dates = scrapy.Field()
    ca_complaint_info = scrapy.Field()
    ca_inspect_typea = scrapy.Field()
    ca_inspect_typeb = scrapy.Field()
    ca_other_typea = scrapy.Field()
    ca_other_typeb = scrapy.Field()
    # IL specific
    il_provider_id = scrapy.Field()
    il_facility_type = scrapy.Field()
    il_day_age_range = scrapy.Field()
    il_night_age_range = scrapy.Field()
    il_day_capacity = scrapy.Field()
    il_night_capacity = scrapy.Field()

    # Alabama specific fields
    al_quality_rating = scrapy.Field()
    al_rating_expiration = scrapy.Field()
    al_nighttime_hours = scrapy.Field()
    al_nighttime_ages = scrapy.Field()
    al_mailing_address = scrapy.Field()
    al_accreditations = scrapy.Field()
    al_adverse_actions = scrapy.Field()
    al_substantiated_complaints = scrapy.Field()
    al_deficiency_reports = scrapy.Field()

    # Arkansas specific fields
    ar_quality_rating = scrapy.Field()
    ar_program_type = scrapy.Field()
    ar_regulation_type = scrapy.Field()
    ar_total_capacity = scrapy.Field()

    # Colorado specific fields
    co_quality_rating = scrapy.Field()
    co_award_date = scrapy.Field()
    co_governing_body = scrapy.Field()
    co_cccap_fa_status_d1 = scrapy.Field()
    co_cccap_authorization_status = scrapy.Field()
    co_school_district = scrapy.Field()
    co_ecc = scrapy.Field()
    co_ccrr = scrapy.Field()
    co_license_type = scrapy.Field()
    co_licensed_to_serve = scrapy.Field()
    co_special_needs = scrapy.Field()
    co_accepting_new_children = scrapy.Field()
    co_infant_openings = scrapy.Field()
    co_toddler_openings = scrapy.Field()
    co_preschool_openings = scrapy.Field()
    co_school_age_openings = scrapy.Field()
    co_head_start = scrapy.Field()
    co_license_issue_date = scrapy.Field()

    # New York specific fields
    ny_facility_id = scrapy.Field()
    ny_region_code = scrapy.Field()
    ny_facility_opened_date = scrapy.Field()
    ny_address_omitted = scrapy.Field()
    ny_phone_number_omitted = scrapy.Field()
    ny_phone_extension = scrapy.Field()
    ny_school_district_name = scrapy.Field()
    ny_capacity_description = scrapy.Field()

    # Pennsylvania specific fields
    pa_stars_rating = scrapy.Field()
    pa_certificate_status = scrapy.Field()
    pa_school_district = scrapy.Field()
    pa_meal_options = scrapy.Field()
    pa_schedule = scrapy.Field()
    pa_cost_table = scrapy.Field()

    # New Mexico specific fields
    nm_star_level = scrapy.Field()
    nm_potty_training = scrapy.Field()
    nm_pay_schedules = scrapy.Field()
    nm_snacks = scrapy.Field()
    nm_meals = scrapy.Field()
    nm_schedule = scrapy.Field()

    # Utah specific fields
    ut_license_type = scrapy.Field()
    ut_quality_rating = scrapy.Field()
    ut_vacancies = scrapy.Field()
    ut_licensed_since = scrapy.Field()
    ut_environment = scrapy.Field()
    ut_meals = scrapy.Field()
    ut_school_district = scrapy.Field()

    # Montana specific fields
    mt_license_type = scrapy.Field()

    # Maryland specific fields
    md_approved_education = scrapy.Field()
    md_accreditation = scrapy.Field()
    md_fatalities = scrapy.Field()
    md_serious_injuries = scrapy.Field()
    md_excels_level = scrapy.Field()
    md_school_name = scrapy.Field()

    # Michigan specific fields
    mi_license_status = scrapy.Field()
    mi_licensee_address = scrapy.Field()
    mi_services_provided = scrapy.Field()
    mi_full_day = scrapy.Field()

    # Minnesota specific fields
    mn_last_renewed_date = scrapy.Field()
    mn_licensed_to_provide = scrapy.Field()
    mn_restrictions = scrapy.Field()
    mn_setting = scrapy.Field()
    mn_gender = scrapy.Field()
    mn_license_info_misc = scrapy.Field()
    mn_type_of_license = scrapy.Field()
    mn_license_holder_onsite = scrapy.Field()

    # Georgia specific fields
    ga_quality_rated_level = scrapy.Field()
    ga_accepting_new_children = scrapy.Field()
    ga_liability_insurance = scrapy.Field()
    ga_mailing_address = scrapy.Field()
    ga_registration_fee = scrapy.Field()
    ga_activity_fee = scrapy.Field()
    ga_program_status = scrapy.Field()
    ga_compliance_status = scrapy.Field()
    ga_services = scrapy.Field()
    ga_transportation = scrapy.Field()
    ga_meals = scrapy.Field()
    ga_accreditation = scrapy.Field()
    ga_environment = scrapy.Field()
    ga_summer_camp = scrapy.Field()
    ga_accepts_children_type = scrapy.Field()
    ga_profit_status = scrapy.Field()
    ga_weekly_rates = scrapy.Field()
    ga_activities = scrapy.Field()
    ga_other_care_type = scrapy.Field()
    ga_financial_info = scrapy.Field()
    ga_special_hours = scrapy.Field()
    ga_curriculum = scrapy.Field()
    ga_family_engagement = scrapy.Field()
    ga_operating_months = scrapy.Field()
    ga_operating_days = scrapy.Field()
    ga_transportation_notes = scrapy.Field()
    ga_school_break_notes = scrapy.Field()

    # Washington specific fields
    wa_provider_id = scrapy.Field()
    wa_license_name = scrapy.Field()
    wa_license_type = scrapy.Field()
    wa_early_achievers_status = scrapy.Field()
    wa_school_district = scrapy.Field()
    wa_head_start = scrapy.Field()
    wa_early_head_start = scrapy.Field()
    wa_eceap = scrapy.Field()
    wa_available_slots = scrapy.Field()
    wa_slot_age_groups = scrapy.Field()
    wa_food_program = scrapy.Field()
    wa_subsidy = scrapy.Field()
    wa_provider_status = scrapy.Field()
    wa_languages_of_instruction = scrapy.Field()
    wa_contacts = scrapy.Field()
    wa_license_history = scrapy.Field()

    # South Carolina specific fields
    sc_provider_id = scrapy.Field()
    sc_abc_quality_rating = scrapy.Field()
    sc_abc_rating_history = scrapy.Field()
    sc_program_participation = scrapy.Field()
    sc_license_category = scrapy.Field()
    sc_licensing_specialist_name = scrapy.Field()
    sc_licensing_specialist_phone = scrapy.Field()

    # New Jersey specific fields (from GetProviders.aspx)
    nj_unique_program_id = scrapy.Field()
    nj_program_facility_type = scrapy.Field()
    nj_facility_type = scrapy.Field()
    nj_license_type = scrapy.Field()
    nj_quality_rating = scrapy.Field()
    nj_accreditation = scrapy.Field()
    nj_yearly_schedule = scrapy.Field()
    nj_doh_id = scrapy.Field()
    nj_phone_extension = scrapy.Field()
    nj_participation_programs = scrapy.Field()
    nj_curriculum = scrapy.Field()
    nj_child_assessment = scrapy.Field()
    nj_environmental_features = scrapy.Field()
    nj_meal_options = scrapy.Field()
    nj_special_needs_training = scrapy.Field()
    nj_transportation = scrapy.Field()
    nj_special_schedules = scrapy.Field()
    nj_discounts = scrapy.Field()
    nj_fees = scrapy.Field()
    nj_mccyn_plus = scrapy.Field()
    nj_social_media = scrapy.Field()
    nj_tuition_infant_hourly = scrapy.Field()
    nj_tuition_infant_daily = scrapy.Field()
    nj_tuition_infant_weekly = scrapy.Field()
    nj_tuition_infant_monthly = scrapy.Field()
    nj_tuition_toddler_hourly = scrapy.Field()
    nj_tuition_toddler_daily = scrapy.Field()
    nj_tuition_toddler_weekly = scrapy.Field()
    nj_tuition_toddler_monthly = scrapy.Field()
    nj_tuition_preschool_hourly = scrapy.Field()
    nj_tuition_preschool_daily = scrapy.Field()
    nj_tuition_preschool_weekly = scrapy.Field()
    nj_tuition_preschool_monthly = scrapy.Field()
    nj_tuition_school_age_hourly = scrapy.Field()
    nj_tuition_school_age_daily = scrapy.Field()
    nj_tuition_school_age_weekly = scrapy.Field()
    nj_tuition_school_age_monthly = scrapy.Field()

    # Rhode Island specific fields
    ri_brightstars_rating = scrapy.Field()
    ri_license_decision = scrapy.Field()
    ri_most_recently_renewed = scrapy.Field()
    ri_ccap_status = scrapy.Field()
    ri_ccap_expiration_date = scrapy.Field()
    ri_head_start = scrapy.Field()
    ri_state_prek = scrapy.Field()
    ri_is_lea = scrapy.Field()
    ri_provider_contact_name = scrapy.Field()
    ri_provider_email = scrapy.Field()
    ri_services_offered = scrapy.Field()
    ri_availability = scrapy.Field()
    ri_age_group_capacity = scrapy.Field()

    # North Carolina specific fields
    nc_license_type = scrapy.Field()
    nc_license_effective_date = scrapy.Field()
    nc_star_rating_total_points = scrapy.Field()
    nc_star_rating_max_points = scrapy.Field()
    nc_program_standards_points = scrapy.Field()
    nc_educational_standards_points = scrapy.Field()
    nc_capacity_first_shift = scrapy.Field()
    nc_capacity_second_shift = scrapy.Field()
    nc_capacity_third_shift = scrapy.Field()
    nc_license_restrictions = scrapy.Field()
    nc_license_history = scrapy.Field()
    nc_special_features = scrapy.Field()
    nc_staff_child_ratios = scrapy.Field()
    nc_owner_name = scrapy.Field()
    nc_owner_mailing_address = scrapy.Field()
    nc_owner_phone = scrapy.Field()
    nc_owner_fax = scrapy.Field()
    nc_owner_email = scrapy.Field()
    nc_sanitation_inspection_date = scrapy.Field()
    nc_sanitation_classification = scrapy.Field()
    nc_sanitation_score = scrapy.Field()

    # West Virginia specific fields
    wv_licensing_specialist = scrapy.Field()
    wv_license_type = scrapy.Field()
    wv_contact = scrapy.Field()
    wv_contact_title = scrapy.Field()
    wv_age_from = scrapy.Field()
    wv_age_to = scrapy.Field()

    # Arizona specific fields
    az_facility_id = scrapy.Field()
    az_operatinghourid = scrapy.Field()
    az_affiliation = scrapy.Field()
    az_regionalpartnership = scrapy.Field()
    az_shiftcomment = scrapy.Field()
    az_headstart = scrapy.Field()
    az_desprovider = scrapy.Field()
    az_status_label = scrapy.Field()
    az_first_slot_start = scrapy.Field()
    az_first_slot_end = scrapy.Field()
    az_license_type = scrapy.Field()

    # Florida specific fields
    fl_dba = scrapy.Field()
    fl_license_status = scrapy.Field()
    fl_alternate_provider_number = scrapy.Field()
    fl_city = scrapy.Field()
    fl_zip_code = scrapy.Field()
    fl_display_address_on_web = scrapy.Field()
    fl_display_email_on_web = scrapy.Field()
    fl_display_phone_on_web = scrapy.Field()
    fl_is_religious_exempt = scrapy.Field()
    fl_is_faith_based = scrapy.Field()
    fl_is_head_start = scrapy.Field()
    fl_is_offering_school_readiness = scrapy.Field()
    fl_is_vpk = scrapy.Field()
    fl_is_gold_seal = scrapy.Field()
    fl_is_public_school = scrapy.Field()
    fl_wels_rating_date = scrapy.Field()
    fl_vpk_school_year_composite_score = scrapy.Field()
    fl_vpk_school_year_wels_rating_date = scrapy.Field()
    fl_vpk_summer_composite_score = scrapy.Field()
    fl_vpk_summer_wels_rating_date = scrapy.Field()
    fl_is_trauma_badge = scrapy.Field()
    fl_is_inclusion_badge = scrapy.Field()
    fl_is_dll_badge = scrapy.Field()
    fl_is_infant_toddler_badge = scrapy.Field()
    fl_trauma_badge_date = scrapy.Field()
    fl_inclusion_badge_date = scrapy.Field()
    fl_dll_badge_date = scrapy.Field()
    fl_infant_toddler_badge_date = scrapy.Field()
    fl_services = scrapy.Field()
    fl_programs = scrapy.Field()
    fl_gold_seal = scrapy.Field()
    fl_vpk_accreditation = scrapy.Field()
    fl_vpk_classrooms = scrapy.Field()
    fl_vpk_curriculum = scrapy.Field()
    fl_vpk_instructor_credentials = scrapy.Field()

    # These fields help with tracking and debugging.
    provider_url = scrapy.Field()
    source_state = scrapy.Field()

    # This will hold the list of inspections.
    inspections = scrapy.Field()
