"""Generate ``SOURCES.md`` (per-state data-source provenance).

This is a **build artifact generator**: it introspects every spider and emits a
markdown table mapping each state to the source website(s) it scrapes. The
sources are read off each spider's ``allowed_domains`` (falling back to the
hosts in ``start_urls``). Most states have a single source; a few list an
additional enrichment source (e.g. Maryland's EXCELS API, Virginia's quality
site), which shows up as a second declared domain.

A handful of spiders build their requests dynamically and declare neither
``allowed_domains`` nor ``start_urls`` at the class level; their source host is
recorded in ``SOURCE_OVERRIDES`` below and must be kept in sync by hand.

Run:  ``.venv/bin/python scripts/generate_sources.py``

Determinism: the output must be byte-for-byte identical on every run for the
same code (a pytest drift-guard depends on it). No timestamps/hostnames/paths;
spiders are emitted in sorted order and each state's declared domain order is
preserved (it is fixed by the source code).

Shipped with the dataset: ``run_spiders.sh -u`` regenerates this file and
uploads it alongside the data via ``upload_to_huggingface.py --extra-file``.
"""
import argparse
import os
import sys
from urllib.parse import urlparse

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if REPO_ROOT not in sys.path:
    sys.path.insert(0, REPO_ROOT)
# Make spider discovery independent of the current working directory (the
# drift-guard test and run_spiders.sh both call this from varying cwds).
os.environ.setdefault("SCRAPY_SETTINGS_MODULE", "provider_scrape.settings")

from scrapy.spiderloader import SpiderLoader  # noqa: E402
from scrapy.utils.project import get_project_settings  # noqa: E402

OUTPUT_PATH = os.path.join(REPO_ROOT, "SOURCES.md")

# Source host(s) for spiders that declare neither ``allowed_domains`` nor
# ``start_urls`` at the class level (they build requests dynamically). Keep in
# sync with the domain each spider actually hits.
SOURCE_OVERRIDES = {
    "illinois": ["sunshine.dcfs.illinois.gov"],
    "minnesota": ["licensinglookup.dhs.state.mn.us"],
    "texas": ["childcare.hhs.texas.gov"],
}


def spider_loader():
    return SpiderLoader.from_settings(get_project_settings())


def state_label(spider_name):
    """``new_york`` -> ``New York`` (state names title-case cleanly)."""
    return spider_name.replace("_", " ").title()


def sources_for_spider(cls, spider_name):
    """Ordered, de-duped list of source hosts for a spider.

    Prefers ``allowed_domains`` (the canonical source list, including any
    enrichment domain); falls back to the hosts parsed from ``start_urls``, then
    to ``SOURCE_OVERRIDES`` for spiders that declare neither.
    """
    hosts = []

    def add(host):
        host = (host or "").strip()
        if host and host not in hosts:
            hosts.append(host)

    for domain in getattr(cls, "allowed_domains", None) or []:
        add(domain)
    if not hosts:
        for url in getattr(cls, "start_urls", None) or []:
            add(urlparse(url).netloc)
    if not hosts:
        for host in SOURCE_OVERRIDES.get(spider_name, []):
            add(host)
    return hosts


def collect_rows():
    """Return sorted ``(state_label, [source_host, ...])`` rows, one per spider."""
    loader = spider_loader()
    rows = []
    for spider_name in sorted(loader.list()):
        cls = loader.load(spider_name)
        rows.append((state_label(spider_name),
                     sources_for_spider(cls, spider_name)))
    return rows


def md_escape(value):
    return str(value).replace("|", "\\|")


def render_sources(hosts):
    if not hosts:
        return "—"
    return "<br>".join("https://%s/" % md_escape(h) for h in hosts)


def build_markdown():
    lines = []
    add = lines.append

    add("# Data Sources")
    add("")
    add("<!-- DO NOT EDIT BY HAND. Generated by "
        "`scripts/generate_sources.py`. -->")
    add("")
    add("The source website(s) scraped for each state, derived from each "
        "spider's `allowed_domains` / `start_urls`. Most states have a single "
        "source; a few list an additional enrichment source.")
    add("")
    add("To regenerate: `.venv/bin/python scripts/generate_sources.py`.")
    add("")
    add("| State | Source(s) |")
    add("|---|---|")
    for label, hosts in collect_rows():
        add("| %s | %s |" % (md_escape(label), render_sources(hosts)))
    add("")

    return "\n".join(lines).rstrip("\n") + "\n"


def build_arg_parser():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--output", default=OUTPUT_PATH,
                        help="path to write the sources markdown "
                             "(default: %(default)s)")
    return parser


def main(argv=None):
    args = build_arg_parser().parse_args(argv)
    markdown = build_markdown()
    with open(args.output, "w", encoding="utf-8") as handle:
        handle.write(markdown)
    print("Wrote %s" % args.output)
    return 0


if __name__ == "__main__":
    sys.exit(main())
