"""Generate ``state_pipeline_details.md`` (the as-built pipeline reference).

This is a **build artifact generator**: it introspects ``items.py`` +
``normalization.py`` and emits markdown documenting, for every field, the exact
transformation the normalization pipeline applies, plus the per-state field
mappings. Humans maintain only the curated explanations in
``provider_scrape/field_docs.py``.

Run:  ``.venv/bin/python scripts/generate_pipeline_details.py``

Determinism: the output must be byte-for-byte identical on every run for the
same code (a pytest drift-guard depends on it). No timestamps/hostnames/paths;
everything is emitted in a fixed, sorted order. Stdlib only.
"""
import os
import re
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if REPO_ROOT not in sys.path:
    sys.path.insert(0, REPO_ROOT)

from provider_scrape import normalization as norm  # noqa: E402
from provider_scrape.field_docs import FIELD_DOCS  # noqa: E402
from provider_scrape.items import InspectionItem, ProviderItem  # noqa: E402

OUTPUT_PATH = os.path.join(REPO_ROOT, "state_pipeline_details.md")

STATE_PREFIX_RE = re.compile(r"^[a-z]{2}_")
TRACKING_FIELDS = ("inspections", "provider_url", "source_state")

# Derived (additive) common fields and their source.
DERIVED_FIELDS = (
    ("facility_category", "provider_type"),
    ("city", "address"),
    ("state", "address"),
    ("zip", "address"),
    # Populated by the post-run geocoding enrichment step (geocoding.py), not
    # the normalization pipeline; keyed off address.
    ("geocode_source", "address"),
    ("geocode_confidence", "address"),
)
DERIVED_FIELD_NAMES = {name for name, _ in DERIVED_FIELDS}

# USPS code -> spelled-out state name, inverted from normalization's table so
# the per-state headers stay derived from existing code.
_CODE_TO_NAME = {code: name for name, code in norm.SPELLED_STATE_TO_USPS.items()}


def is_state_specific(field):
    return bool(STATE_PREFIX_RE.match(field))


def common_provider_fields():
    """ProviderItem fields that are neither state-specific nor tracking."""
    return sorted(
        f for f in ProviderItem.fields
        if not is_state_specific(f) and f not in TRACKING_FIELDS
        and f not in DERIVED_FIELD_NAMES
    )


def collapse_source_to_common():
    mapping = {}
    for common, sources in norm.FIELD_COLLAPSE_MAP.items():
        for source in sources:
            mapping[source] = common
    return mapping


def transformation_for(field):
    """Infer the transformation label for a common field from the code."""
    collapse_targets = set(norm.FIELD_COLLAPSE_MAP)
    if field in norm.NAME_FIELDS:
        tags = ["Whitespace cleanup", "Title Case (ALL-CAPS names)"]
    elif field in norm.DATE_FIELDS:
        tags = ["Whitespace cleanup", "ISO 8601 date"]
    elif field == norm.CAPACITY_FIELD:
        tags = ["Whitespace cleanup", "Integer coercion"]
    elif field == norm.AGES_SERVED_FIELD:
        tags = ["Whitespace cleanup", "List -> string"]
    elif field in norm.COORDINATE_FIELDS:
        tags = ["Whitespace cleanup", "Coordinate -> string"]
    elif field == "status":
        tags = ["Whitespace cleanup", "Controlled vocabulary (status)"]
    elif field == "provider_type":
        tags = ["Whitespace cleanup", "Preserved (drives facility_category)"]
    elif field == "address":
        tags = ["Whitespace cleanup", "Address cleanup",
                "Component parse -> city/state/zip"]
    elif field in collapse_targets:
        label = "Field collapse from state-specific source"
        if field in norm._BOOLEAN_COLLAPSE_FIELDS:
            label += " (-> boolean)"
        tags = ["Whitespace cleanup", label]
    else:
        tags = ["Whitespace cleanup"]
    return "; ".join(tags)


def explanation_for(field, transformation):
    doc = FIELD_DOCS.get(field)
    if doc:
        return doc
    return ("%s. **TODO:** add a curated explanation to "
            "`provider_scrape/field_docs.py`." % transformation)


def md_escape(value):
    return str(value).replace("|", "\\|")


def build_markdown():
    lines = []
    add = lines.append

    add("# State Pipeline Details (as-built)")
    add("")
    add("<!-- DO NOT EDIT BY HAND. Generated by "
        "`scripts/generate_pipeline_details.py`. -->")
    add("")
    add("This file records what the normalization pipeline actually does to "
        "each field, plus per-state field mappings. It is **generated** from "
        "`provider_scrape/items.py` and `provider_scrape/normalization.py`; "
        "the only hand-authored content is the explanations in "
        "`provider_scrape/field_docs.py`.")
    add("")
    add("For guidance on *where new data should go*, see "
        "[`docs/field_mapping_playbook.md`](docs/field_mapping_playbook.md).")
    add("")
    add("To regenerate: `.venv/bin/python scripts/generate_pipeline_details.py`.")
    add("")

    # --- Common-field transformations ---
    add("## Common-field transformations")
    add("")
    add("| Field | Transformation | Explanation |")
    add("|---|---|---|")
    for field in common_provider_fields():
        transformation = transformation_for(field)
        explanation = explanation_for(field, transformation)
        add("| `%s` | %s | %s |"
            % (field, md_escape(transformation), md_escape(explanation)))
    add("")
    add("> Inspections are normalized too: every string value gets whitespace "
        "cleanup, and the date fields (%s) are converted to ISO 8601. The "
        "`status` vocabulary does not apply to inspections."
        % ", ".join("`%s`" % f for f in norm.INSPECTION_DATE_FIELDS))
    add("")
    add("> Tracking fields (%s) are passed through unchanged."
        % ", ".join("`%s`" % f for f in TRACKING_FIELDS))
    add("")

    # --- Derived fields ---
    add("## Derived fields (additive)")
    add("")
    add("These canonical fields are derived from a source field; the source is "
        "preserved unchanged.")
    add("")
    add("| Field | Derived from | Explanation |")
    add("|---|---|---|")
    for field, source in DERIVED_FIELDS:
        explanation = explanation_for(field, "Derived from %s" % source)
        add("| `%s` | `%s` | %s |"
            % (field, source, md_escape(explanation)))
    add("")

    # --- Field-collapse map ---
    add("## Field-collapse map")
    add("")
    add("Each common field is populated from a single populated source field "
        "(additive — the source field is kept). Rendered from "
        "`FIELD_COLLAPSE_MAP`.")
    add("")
    add("| Common field | Source state-specific fields |")
    add("|---|---|")
    for common in sorted(norm.FIELD_COLLAPSE_MAP):
        sources = ", ".join("`%s`" % s
                            for s in sorted(norm.FIELD_COLLAPSE_MAP[common]))
        add("| `%s` | %s |" % (common, sources))
    add("")

    # --- Controlled-vocabulary appendices ---
    add("## Controlled vocabulary: `status`")
    add("")
    add("Raw status values mapped to each canonical bucket "
        "(replaced in place; unmapped -> `unknown`).")
    add("")
    add("| Canonical | Raw values |")
    add("|---|---|")
    for canonical in sorted(norm.STATUS_BUCKETS):
        raws = ", ".join("`%s`" % md_escape(r)
                         for r in sorted(norm.STATUS_BUCKETS[canonical]))
        add("| `%s` | %s |" % (canonical, raws))
    add("")

    add("## Controlled vocabulary: `facility_category`")
    add("")
    add("Raw `provider_type` values mapped to each canonical category "
        "(additive; unmapped -> `other`).")
    add("")
    add("| Canonical | Raw provider_type values |")
    add("|---|---|")
    for canonical in sorted(norm.FACILITY_CATEGORY_BUCKETS):
        raws = ", ".join(
            "`%s`" % md_escape(r)
            for r in sorted(norm.FACILITY_CATEGORY_BUCKETS[canonical]))
        add("| `%s` | %s |" % (canonical, raws))
    add("")

    # --- Per-state section ---
    add("## Per-state fields")
    add("")
    add("State-specific fields (matched by the `xx_` prefix) across "
        "`ProviderItem` and `InspectionItem`, each marked as collapsing into a "
        "common field or passing through unchanged.")
    add("")
    source_to_common = collapse_source_to_common()
    all_state_fields = sorted(
        {f for f in ProviderItem.fields if is_state_specific(f)}
        | {f for f in InspectionItem.fields if is_state_specific(f)}
    )
    by_state = {}
    for field in all_state_fields:
        by_state.setdefault(field[:2], []).append(field)

    for code in sorted(by_state):
        name = _CODE_TO_NAME.get(code.upper())
        header = "%s (%s)" % (name.title(), code.upper()) if name \
            else code.upper()
        add("### %s" % header)
        add("")
        for field in sorted(by_state[code]):
            common = source_to_common.get(field)
            if common:
                add("- `%s` -> collapses into `%s`" % (field, common))
            else:
                add("- `%s` -> pass-through" % field)
        add("")

    return "\n".join(lines).rstrip("\n") + "\n"


def main():
    markdown = build_markdown()
    with open(OUTPUT_PATH, "w", encoding="utf-8") as handle:
        handle.write(markdown)
    print("Wrote %s" % OUTPUT_PATH)


if __name__ == "__main__":
    main()
